// DO NOT EDIT.
// Generated by github.com/worldiety/whatwg

// +build js,wasm

package dom

import "syscall/js"

type Event interface {
	// Type_ returns the value of type_.
	Type_() string

	// Target returns the value of target or nil.
	Target() EventTarget

	// SrcElement returns the value of srcElement or nil.
	SrcElement() EventTarget

	// CurrentTarget returns the value of currentTarget.
	CurrentTarget() EventTarget

	// EventPhase returns the value of eventPhase.
	EventPhase() uint16

	// CancelBubble returns the value of cancelBubble.
	CancelBubble() bool

	// SetCancelBubble updates the cancelBubble value.
	SetCancelBubble(value bool)

	// Bubbles returns the value of bubbles.
	Bubbles() bool

	// Cancelable returns the value of cancelable.
	Cancelable() bool

	// ReturnValue returns the value of returnValue.
	ReturnValue() bool

	// SetReturnValue updates the returnValue value.
	SetReturnValue(value bool)

	// DefaultPrevented returns the value of defaultPrevented.
	DefaultPrevented() bool

	// Composed returns the value of composed.
	Composed() bool

	// IsTrusted returns the value of isTrusted.
	IsTrusted() bool

	// TimeStamp returns the value of timeStamp.
	TimeStamp() bool
}
type eventWrapper struct {
	val js.Value
}

func NewEvent(type_ string, eventInitDict EventInit) Event {
	val := js.Global().New("Event", type_, eventInitDict)
	return eventWrapper{val: val}
}
func WrapEvent(val js.Value) Event {
	return eventWrapper{val: val}
}
func (e eventWrapper) Type_() string {
}

func (e eventWrapper) Target() EventTarget {
}

func (e eventWrapper) SrcElement() EventTarget {
}

func (e eventWrapper) CurrentTarget() EventTarget {
}

func (e eventWrapper) EventPhase() uint16 {
}

func (e eventWrapper) CancelBubble() bool {
}

func (e eventWrapper) SetCancelBubble(val bool) {
}

func (e eventWrapper) Bubbles() bool {
}

func (e eventWrapper) Cancelable() bool {
}

func (e eventWrapper) ReturnValue() bool {
}

func (e eventWrapper) SetReturnValue(val bool) {
}

func (e eventWrapper) DefaultPrevented() bool {
}

func (e eventWrapper) Composed() bool {
}

func (e eventWrapper) IsTrusted() bool {
}

func (e eventWrapper) TimeStamp() bool {
}

type EventInit struct {
	Bubbles    bool
	Cancelable bool
	Composed   bool
}
